# Introduction to the Python programming language

In this notebook we will cover the basics principals of python, both in terms of development and philosophy. We will focus primarily on Python 3.

## 1. What is Python?

[Python is an interpreted, object-oriented, high-level programming language with dynamic semantics.](https://www.python.org/doc/essays/blurb/)

First appearing in 1991, Python was designed by [Guido van Rossum](https://gvanrossum.github.io/).

Python is interpreted. Unlike C and like programming languages which must be compiled, Python code is executed directly by a Python interpreter rather than a machine. As a high-level language, Python is also far-removed from the challenges associated with lower-level programming languages (such as assembly languages), making it much easier to learn.

Python is further defined as an object-oriented language with dynamic semantics, what does that mean? In the next section we will review Python semantics and then tackle [Object Oriented Programming](https://en.wikipedia.org/wiki/Object-oriented_programming)

## 2. Python semantics

So what's the connection between a programming language and semantics anyway? In programming, when we talk about [semantics](https://en.wikipedia.org/wiki/Semantics_(computer_science)) we are often concerned about what is _[syntactically](https://en.wikipedia.org/wiki/Syntax_(programming_languages)) valid_ in a given language. So then, what's considered "syntactically valid" in Python. For instance, if I wanted to write a small Python program that would just display the text "Hello, world!" on my screen, what would that look like?

Let's get our first glimps at the Python programming language, and then we can discuss our observation.

The below cell is an *executable cell*. You can select it and press `run` to execute a block of Python code. Try executing the next cell.

In [464]:
"Hello, world!"

'Hello, world!'

Well, that doesn't look much like a program, does it. But in fact, what you just observed is the foundation of Python and all [_imperative programming languages_](https://en.wikipedia.org/wiki/Imperative_programming). Wait, I thought we said Python was object oriented, why are we now calling it _imperative_. In fact, most object oriented languages are also imperative by their very nature. Let's consider why this matters, and how imperative programming relates to the code block we just executed above.

First, consider what "imperative programming" means. Imperative languages are based on statements, and those statements determine the [flow of control](https://en.wikipedia.org/wiki/Control_flow) within a program. A statement that controls something? That probably sounds familiar, often we call these **instructions**, you can think of statements as instructions or micro instructions if you like. All actions within an imperative program are caused by, and only only occure because of, a given statement which produced the action. In other words, the program is strictly controlled by instructions.

Above, you saw that philosophy in action, we declared the instruction (to print) _"Hello, world!"_ and we got back the output _"Hello, world!"_
Our statement directly controlled what was output by the program. Try changing the code block above and see what outputs you can get. Afterward, we can consider the kinds of statements available in Python below.

### 2.1 Python statements

Programs in Python consists of lines composed of statements, which can be of the following type:

- [simple statements](https://docs.python.org/3/reference/simple_stmts.html), such as a(n):
    - [expression](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-expression-stmt); [see also](https://docs.python.org/3/reference/expressions.html), as demonstrated in [#2.](#2.-Python-semantics)
    - [assert](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-assert-stmt)
    - [assignment](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-assignment-stmt)
    - [pass](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-pass-stmt)
    - [delete](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-del-stmt)
    - [return](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-return-stmt)
    - [yield](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-yield-stmt)
    - [raise](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-raise-stmt)
    - [break](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-break-stmt)
    - [continue](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-continue-stmt)
    - [import](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-import-stmt)
    - [future](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-future-stmt)
    - [global](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-global-stmt)
    - [nonlocal](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-nonlocal-stmt)
- [compound statements](https://docs.python.org/3/reference/compound_stmts.html), such as a(n):
    - [if](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-if-stmt)
    - [while](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-while-stmt)
    - [for](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-for-stmt)
    - [try](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-try-stmt)
    - [with](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-with-stmt)
    - [function definition](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-funcdef)
    - [class definition](https://docs.python.org/3/reference/compound_stmts.html#grammar-token-classdef)
    - [co-routine](https://docs.python.org/3/reference/compound_stmts.html#coroutines)


We will not consider all of these statements in this lesson, but I encourage you to look at the documentation linked above for yourself.

We can start our Python journey with expressions, we've already seen how expressions work, though to a limited degree. Below we will examine expressions in more detail.

#### 2.1.1 Expressions

Expression statements are used to compute a value, write a value, or call a function. For instance observe the function call below.

In [465]:
print(1234)

1234


Above, we used a statement (remember, an instruction) that looks like this: `print(1234)`. This statement executed a type of function known as a procedure. That procedure did two thing, it printed `1234`, it's own input, into our output and then it returned a value, in that order. Wait, what value? Nothing happened besides the outputting of `1234`, right?

Observe the following code block and prove to yourself that two actions did indeed occur, though one was ignored in the previous code block. We will compose a statement that looks like this: `print(print(1234))`. Remember, we observed that the [`print`](https://docs.python.org/3/library/functions.html#print) procedure takes it's own input and outputs it again, so what will be the output of these two procedures? Try to figure it out on your own before running the below code block.

In [466]:
print(print(1234))

1234
None


Above we called the `print` procedure two times, once on the input `1234` and a second time, on the input of the _**returned value**_ of the procedure `print(1234)`. What do we observe? The `print` procecdure caused `1234` to be output by our program, yes, but it also returns a value we did not write ourselves, `None`.

You do not need to understand _how_ or _why_ a value was returned just yet, but you should understand that all functions, including procedures, return a value in Python, and _all procedures return `None`_.

Also note that in a Jupyter notebook (or Python in interactive mode), the final expression in a code block is printed to the output, as if it were the input to a `print` procedure, _if the returned value is not `None`_. The below cell, for instance, will not produce an output, because the final expression evaluates to `None`.

The Python docs describe this behaviour this way: 

> In interactive mode, if the value is not `None`, it is converted to a string using the built-in `repr()` function and the resulting string is written to standard output on a line by itself (except if the result is None, so that procedure calls do not cause any output.)

Pay attention to that bit about converting the value to a string, later on you'll see how that causes some funny behaviour if you try to substitute this interactive Python feature for the tried and true `print` procedure.

In [467]:
'This text will not print.'
None

Besides printing values, you will often need to perform practical operations as a Python developer. For instance, you may have to perform mathimatical operations in Python. This can also be accomplished using Python expression statements. Consider the following code blocks.

In [468]:
1 + 1

2

In [469]:
2 - 2

0

In [470]:
5 * 2

10

In [471]:
100 / 10

10.0

In [472]:
2**8

256

Above, we performed a number of simple addition, subtraction, multiplication, division, and exponential operations using Python expression statements. We observe that the returned value of these operations is their solution.

You may have noticed something funny about one of the outputs. While `5 * 2` outputs `10`, `100 / 10` outputs `10.0`. Why the discrepancy here? Consider the following cells. Here we will be using the [`type`](https://docs.python.org/3/library/functions.html?highlight=type#type) function. Note that type is not a _procedure_ like `print`. `type` **returns** a value. Run the cells below, and see if you can figure out the meaning of the returned value of the `type` function.

In [473]:
type(10)

int

In [474]:
type(10.0)

float

Above we observe that numbers containing decimals are classified under the "type" `float`, or floating-point numbers, while numbers without decimals are classified as `int`, or integers. 

Note that like the `None` which we printed earlier using two `print` procedures, you did not explicitly tell Python that `10` is an `int` and `10.0` is a `float`. Rather, [these types are built into the Python programming language](https://docs.python.org/3/library/stdtypes.html#built-in-types). Other types also exist, for instance, sequences (or strings) of characters wrapped in quotes fall under the [`str`](https://docs.python.org/3/library/stdtypes.html#str) type.

In [475]:
type('Hello, world!')

str

In [476]:
type('a')

str

A sequence of arbitrary data not wrapped in quotes can take the form of a [`list`](https://docs.python.org/3/library/stdtypes.html#list), a [`tuple`](https://docs.python.org/3/library/stdtypes.html?highlight=tuple#tuple), a [`set`](https://docs.python.org/3/library/stdtypes.html?highlight=tuple#set-types-set-frozenset), or a [`range`](https://docs.python.org/3/library/stdtypes.html?highlight=tuple#ranges).

In [477]:
type([1])

list

In [478]:
type([1.1, 2.1, 3.1, 4.1])

list

In [479]:
type(['a', 1, 'c', 2])

list

In [480]:
type(('a', None, 'c', 'd'))

tuple

In [481]:
type(set([1, 2, 'Hello']))

set

In [482]:
type(range(10))

range

It's good to remember though that at their root, a `str`, `list`, `tuple`, `set`, and `range` are all sequences, and therefore share common qualities and characteristics.

`None` has the type `NoneType`.

In [483]:
type(None)

NoneType

Key-value pairs in the form of a hash map, also have a type, known as a `dict`, or dictionary in Python.

In [484]:
type({'a': 1, 'b': 2})

dict

Further, boolean values `True` and `False` have the `int` sub-type known as `bool`, or boolean.

In [485]:
type(True)

bool

In [486]:
type(False)

bool

You can prove to yourself that `True` and `False` are indeed `int` types at heart by using them in arithmetic operations as demonstrated in the cells below.

In [487]:
10 - True

9

In [488]:
True + True

2

In [489]:
10 * False

0

In [490]:
True / 2

0.5

Python's principal built-in types are numerics, sequences, mappings, classes, instances and exceptions.

These built-in types are often _refered to_ as [primitive data types](https://en.wikipedia.org/wiki/Primitive_data_type). You are encouraged to read more about these types of data. However, as you may have noticed in the Python documentation, the concept of true primatives does not really exist in Python, in fact, technically speaking, primatives are not even a feature of the Python programming language. We said that Python is an object-oriented programming language, and while not the case for all such languages, [all data in a Python program is represented by objects or by relations between objects](https://docs.python.org/3/reference/datamodel.html#data-model). You can prove this to yourself by running the following cells.

In [491]:
print('Hello'.__doc__)

str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.


In [492]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

You will definitely use some data types more than others. For instance, it would not be that strange if a program never used a `range` at all, but it would be very unlikely that any Python program would not use a `bool`, explicitly or otherwise, at least at some point in the program. Consider for instance our final expressions in this section, [value comparisons](https://docs.python.org/3/reference/expressions.html#value-comparisons), [membership test operations](https://docs.python.org/3/reference/expressions.html#membership-test-operations), and [identity comparisons](https://docs.python.org/3/reference/expressions.html#is-not). 

Value comparisons:
> The operators `<`, `>`, `==`, `>=`, `<=`, and `!=` compare the values of two objects. The objects do not need to have the same type.

Membership test operations:
> The operators `in` and `not in` test for membership. `x in s` evaluates to `True` if `x` is a member of `s`, and False otherwise... All built-in sequences and set types support this as well as dictionary, for which `in` tests whether the dictionary has a given key. For container types such as `list`, `tuple`, `set`, `frozenset`, `dict`, or `collections.deque`, the expression `x in y` is equivalent to `any(x is e or x == e for e in y)`.

Identity comparisons:
> The operators `is` and `is not` test for an object’s identity: `x is y` is `True` if and only if `x` and `y` are the same object. An Object’s identity is determined using the `id()` function.

You will more than likely at some point be comparing and testing membership in Python. These expressions return data in the type of `bool`. Consider the cells below.

In [493]:
'String' == 'Str' + 'ing'

True

In [494]:
'S' in 'String'

True

In [495]:
1 == 0 + 1**100

True

In [496]:
[] == []

True

In [497]:
{} == dict()

True

In [498]:
1 in [1, 2,] + [3, 4]

True

In [499]:
'a' in {'a': 1, 'b': 2}

True

So far, it seems like everything is `True`!

What would a `False` comparison or membership test look like? Consider the cells below.

In [500]:
'String' == 'string'

False

In [501]:
1 == 10

False

In [502]:
['String'] == []

False

In [503]:
{'a': 1} == {'a': 10}

False

In [504]:
1 in [5, 4, 3]

False

In [505]:
'a' in {}

False

The above cells demonstrate that such tests are fairly logical. First of all, it is clear that for two things to be equal they should evaluate to the same value. Second, for a membership test to pass, the evaluated value must exist in the sequence, set, or container.

So far, we've only tested a few value comparison operators, try out a few on your own. Afterward we'll consider identity comparisons.

We observed earlier that `[] == []` evaluates `True`. This was because two empty `list` objects evaluate to the same thing. But does that make them identical? Consider the cell below.

In [506]:
[] is []

False

Clearly not, but why? We read that `is` is not concerned with the computed value of data, but rather with it's [_identity_](https://docs.python.org/3/library/functions.html#id), in [CPython](https://en.wikipedia.org/wiki/CPython), "This is the address of the object in memory."

In other words, the only way two things are identical is if the refer to the same bit of computer memory. Consider the below block.

In [507]:
x = []
y = x
y is x

True

Now, we are just about to look into assignments, so don't worry too much about what you just saw, just know that `y` and `x` are exactly identical, referencing the same data in memory. This is because `y` was assigned to reference the memory block that `x` is referencing.

You can prove this to yourself by mutating `x` or `y` and observing the effect on it's counterpart.

In [508]:
x += ["Hello"]
y += ["World!"]
print(y)
print(y == x, x is y)

['Hello', 'World!']
True True


Clearly `y` and `x` are not simply equal, but are in fact identical by assignment. We will learn more about assignments in the next section. We will not discuss identity further, so please keep these ideas in mind and test for yourself as we tackle assignment statements.

#### 2.1.2 Assignments

> Assignment statements are used to (re)bind names to values and to modify attributes or items of mutable objects.

Likely, this is not a foreign concept to you. But let's consider assignments through the lens of Python's `dynamic semantics`.

In [509]:
x = 1
print(x, type(x))

x = 1.0
print(x, type(x))

x = 'Hello, world!'
print(x, type(x))

x = [1, "a", {"b": 1}, [1]]
print(x, type(x))

x = {}
print(x, type(x))

x = None
print(x, type(x))

1 <class 'int'>
1.0 <class 'float'>
Hello, world! <class 'str'>
[1, 'a', {'b': 1}, [1]] <class 'list'>
{} <class 'dict'>
None <class 'NoneType'>


Above we see in the simplest form, that a _variable_ can be assigned any arbitrary value. But what else do we see? For one, values can be assigned _dynamically_ irrespective of type. `x` was an `int`, then it was a `float`, then a `str`, then a `list`, then a `dict`, and finally `NoneType`. 

[This post](https://towardsdatascience.com/understanding-and-using-python-classes-3f7e8d1ef2d8) expresses it well:
> objects are instances of values contained into constructs in the code, and they exist at run-time level. Furthermore, we can assign to one object multiple values, since it will update itself, differently from a static semantic language. Namely, if we set `a = 2` and then `a = 'hello'`, the string value will substitute the integer one as soon as the line is executed.

We can also perform operations on these variables and even mutate them, consider the following cells and try to determine the output before running the cells:

In [510]:
y = 1
y = y + 1
print(y)

2


`y = y + 1` can further be simplified to `y += 1` in Python. The same can be done for other arithmetic operations.

In [511]:
y = 1
y += 1
print(y)

2


In [512]:
y = 2
y **= 8
y

256

It probably goes without saying, but also note that _assignments_ are not _expressions_. Therefore, you must explicitly print the variables to observe their values, or you can use the variable in a singular expression. Consider the cell below.

In [513]:
y = "I will not produce any output."

While we're on the topic of assignments, let's think about the data types `list` and `dict`. We know we can easily assign a list, for instance, to a variable, but what about the items within the list? Consider `my_list` below.

In [514]:
my_list = [1, 2, 3, 4]

What if I wanted to change the `int` `4` to the `str` `'Hello, world!'`?

Well, consider the following assignment.

In [515]:
my_list[3] = 'Hello, world!'
my_list

[1, 2, 3, 'Hello, world!']

Well, that works, but how?

Don't over think it, list items can be accessed by their `index`, that is to say, their sequential _position_ in the list, starting from the first value, which has an index of `0` to the last. In Python you can also access indexes using negative numbers, this traverses the list from right to left rather than left to right, starting from `-1`. Observe below.

In [516]:
my_list[-1] = 4
my_list

[1, 2, 3, 4]

The same can be done with `dict` objects. Although here we access the values by referencing the dictionary keys. We can even assign values to _new keys_ that were not in the original dictionary. Consider the following cells.

In [517]:
my_dictionary = {'a': 1, 'b': 2, 'c': 3}
my_dictionary

{'a': 1, 'b': 2, 'c': 3}

In [518]:
my_dictionary['c'] = 'Hello, world!'
my_dictionary

{'a': 1, 'b': 2, 'c': 'Hello, world!'}

In [519]:
my_dictionary['d'] = None
my_dictionary

{'a': 1, 'b': 2, 'c': 'Hello, world!', 'd': None}

Now that you've considered assignments, you may wonder how to remove an assignment all together. Above, for instance, we set the value of the key `d` in `my_dictionary` to `None`. But what if we wanted `d` to not exist at all? What about `my_dictionary` all together? In the next section, we consider the `del` statement, which solves your problem.

#### 2.1.3 Deletions

> Deletion of a name removes the binding of that name from the local or global namespace.

Deletion does just what it sounds like. We delete a value from our program. Consider the below example.

In [520]:
print(my_dictionary)
del my_dictionary['d']
print(my_dictionary)

{'a': 1, 'b': 2, 'c': 'Hello, world!', 'd': None}
{'a': 1, 'b': 2, 'c': 'Hello, world!'}


We observe that the key-value pair `'d': None` is no longer part of the `my_dictionary` object at all. We can further delete the entire dictionary.

In [521]:
print('my_dictionary' in globals())
del my_dictionary
print('my_dictionary' in globals())

True
False


Above, we observe that the dictionary no longer exists after deletion, you can try to print `my_dictionary` yourself to prove that the Python compiler will throw, or return, an error to our output. The error warns us that `my_dictionary` cannot be referenced (it must be declared first) because it does not exist (any more).

So far we've talked a lot about returned values, you have even expirimented with them several times now. In the next section we will consider just what a `return` is.

#### 2.1.4 Returns

> `return` may only occur syntactically nested in a function definition, not within a nested class definition.
> If an expression list is present, it is evaluated, else `None` is substituted.

That statement from the Python docs might be a lot to take in for someone who hasn't even considered function definitions nor class definitions. But don't worry, we'll get there shortly.

For now let's consider the parts we already understand. I will define a function below, and we will call it and see what comes out.

In [522]:
def add1(number):
    """Adds 1 to a number.

    Args:
    number: int or float. The number to be incremented.

    Returns:
    incremented_number: number, plus 1.
    """
    return number + 1

In [523]:
incremented_number = add1(1)
print(incremented_number)

2


When you observe such a simple function, even without knowing exactly what everything means, it is easy to see what is happening. For now, we'll focus just on the `return number + 1` statement.

You probably already see that this is both a `return` statement as well as an arithmetic expression statement, we first increment the `number` variable by `1`, then we _**`return`**_ the value. Last time, we found that the `print` procedure always returned `None`, that's what made it a procedure. The `add1` function on the other hand will always return `number + 1`, that's what makes it a function.

But we're not here to talk about functions just yet, we're here to talk about `return` statements.

Try augmenting the return statement above, for instance try to return a `float` or another data type. Then, try to execute another statement after the return statement, for instance a `print` procedure or another `return` statement. Pay close attention to those indentations too, everyting belonging to that function needs to be indented, or syntactically nested, in it's function definition.

What did you observe? Likely you found that the first `return` puts an end to the function call, nothing after it is evaluated. Further you saw that the `return` statement directly affects the _returned value_.

We can try one more thing, if you haven't already, try to remove the expression portion of the statemeent, `number + 1`, from the `return` statement. Afterward, try to remove the `return` statement all together.

What happened? Observe that in Python, `return` returns a value of `None` if no expression is supplied. Further, `None` is returned even if the `return` statement is not explicitly included.

So far we've seen that expressions, assignments, deletions, and returns are key building blocks of Python programs. You will likely use all of them, maybe with the exception of `del`, in any normal Python program.

However, the limitations of what we've considered so far are fairly obvious. From your exploration of the Python docs, you've seen that there are a number of really useful built-ins, however, what if we want to do more than simple operations?

#### 2.1.5 Imports

The import statement has two forms, the basic `import` form and the `from` form

> The basic import statement (no from clause) is executed in two steps:
> 1. find a module, loading and initializing it if necessary
> 2. define a name or names in the local namespace for the scope where the import statement occurs.

> The from form uses a slightly more complex process:
> 1. find the module specified in the from clause, loading and initializing it if necessary;
> 2. for each of the identifiers specified in the import clauses:
>  1. check if the imported module has an attribute by that name
>  2. if not, attempt to import a submodule with that name and then check the imported module again for that attribute
>  3. if the attribute is not found, ImportError is raised.
>  4. otherwise, a reference to that value is stored in the local namespace, using the name in the as clause if it is present, otherwise using the attribute name

We'll consider first the basic `import` form, and how it might be useful in a simple operation.

Say you wanted to calculate the **factorial** of number. That should be fairly straight forward, maybe `8!`? Well, although it looks good, that expression will actually not accomplish what we want. In fact it results in a syntax error. In this case, the traditional math syntax does not align with Python semantics as it did for addition and subtraction.

In fact, to solve this simple problem, we'd actually need to write a function such as this:

```py
def factorial(number):
    """Calculates the factorial of a positive number.
    
    Args:
    number: positive int. The number in which the factorial is found.
    
    Returns:
    result: The factorial of number.
    """
    result = 1
    for i in range(2, number + 1):
        result *= i
    return result
```

You can copy this code to a executable cell to prove to yourself that it does indeed calculate the factorial of any positive integer.

However, this would be a lot of work if we had to write functions for everything that was not directly built into to the Python language. Fortunately, `imports` provide an easy way to access extra functionality. Consider the cell below.

In [524]:
import math

math.factorial(10)

3628800

What have we done? We've imported something called a [`module`](https://docs.python.org/3/tutorial/modules.html). Specifically, the [`math`](https://docs.python.org/3/library/math.html?highlight=math#module-math) module.

> This module provides access to the mathematical functions defined by the C standard.

importing modules gives us extended functionality in Python without writing cumbersome logic on our own. Often, such modules not only save time, but are also more computationally efficient. Take a moment to think about the kinds of modules that exist in the Python universe.

Let's consider one more import together, and at the same time we can observe the `from` import form. We have already observed the Python `dict` which we learned was a type of collection. We did not talk about it's limitations too much, but it does have one big problem. A `dict` cannot remember the order in which data was inserted into it. This does become a problem when the order of data is important. Consider an alternative collection which we can import from the `collections` module, which addresses this issue. The [OrderedDict](https://www.tutorialsteacher.com/python/collections-module).

> The OrderedDict is similar to a normal dictionary object in Python. However, it remembers the order of the keys in which they were first inserted.

Consider how we import and use the `OrderedDict` collection below.

In [525]:
from collections import OrderedDict

ordered_dictionary = OrderedDict()

ordered_dictionary['c'] = 3
ordered_dictionary['b'] = 2
ordered_dictionary['a'] = 1

ordered_dictionary.keys()

odict_keys(['c', 'b', 'a'])

Above we see that the insertion order is preserved in `ordered_dictionary`, for instance, when accessing a list of it's keys. 

We also see that `OrderedDict` is imported from the `collections` module, and we can access `OrderedDict` directly by using the `from` import form. Notice how the same program can be written without the `from` form.

In [526]:
import collections

ordered_dictionary = collections.OrderedDict()

ordered_dictionary['c'] = 3
ordered_dictionary['b'] = 2
ordered_dictionary['a'] = 1

ordered_dictionary.keys()

odict_keys(['c', 'b', 'a'])

Above, `OrderedDict` is accessed through the `collections` name (or variable) as described in the `import` definition.

Now that you've learned a great deal about syntax, semantics, and simple statements, it's time to dive into [control flow](https://en.wikipedia.org/wiki/Control_flow) with compound statements. 

> Compound statements contain (groups of) other statements; they affect or control the execution of those other statements in some way.

While we did discuss the flow of control earlier in section [#2](#2.-Python-semantics), and of course we have already considered basic control flow through simple statements as demonstrated above. We will now consider groups of statements that make up what many programmers consider traditional control flow constructs.

> The `if`, `while` and `for` statements implement traditional control flow constructs. `try` specifies exception handlers and/or cleanup code for a group of statements, while the `with` statement allows the execution of initialization and finalization code around a block of code. Function and class definitions are also syntactically compound statements.

> A compound statement consists of one or more ‘clauses.’ A clause consists of a header and a ‘suite.’ The clause headers of a particular compound statement are all at the same indentation level. Each clause header begins with a uniquely identifying keyword and ends with a colon. A suite is a group of statements controlled by a clause. A suite can be one or more semicolon-separated simple statements on the same line as the header, following the header’s colon, or it can be one or more indented statements on subsequent lines. Only the latter form of a suite can contain nested compound statements.

#### 2.1.6 If

The `if` statement is possibly one of the easiest compound statements to comprehend.

> The if statement is used for conditional execution.

Consider the cell below.

In [527]:
if 1 == 1:
    print('1 does equal 1')

1 does equal 1


We observe above that the `if` statement above consists of a single clause, containing a header:

```py
if 1 == 1:
```

As well as an indented suite, containing a single statement, a `print` procedure:

```py
    print("1 does equal 1")
```



It is common to use additional clauses with the `if` statement. Namely, `elif` (else if) and `else`.

Consider the following cells.

In [528]:
if 1 == 2:
    print('1 does equal 2')
elif 2 == 1:
    print('2 does equal 1')
elif 1 != 2:
    print('1 does not equal 2')
else:
    print('1 neither equals 2 nor does it not equal 2')

1 does not equal 2


In [529]:
if 1 == 2:
    print('1 does equal 2')
elif 1 > 2:
    print('1 is greater than 2')
else:
    print('1 is neither equal nor greater than 2')

1 is neither equal nor greater than 2


Above we learn two things, first, the `else` clause acts like a catch-all if no other clause's header evaluates to `True`. Second, we see that each clause is considered sequentially, starting from `if`, and once one clause header evaluates to `True`, the _flow of control_ ends, and the `if` statement terminates.

> It selects exactly one of the suites by evaluating the expressions one by one until one is found to be true; then that suite is executed (and no other part of the `if` statement is executed or evaluated). If all expressions are false, the suite of the `else` clause, if present, is executed.

Now that we have a good understanding of `if` statements, let's move onto the slighly more complex `while` statement.

#### 2.1.7 While

> The `while` statement is used for repeated execution as long as an expression is true.

Unlike the `if` statement, which only evaluates the expression in it's clause's header a total of one or zero times, the `while` statement repeatedly tests the expression in it's header until that expression is false.

> This repeatedly tests the expression and, if it is true, executes the first suite; if the expression is false (which may be the first time it is tested) the suite of the `else` clause, if present, is executed and the loop terminates.

Consider the following cell.

In [530]:
i = 0

while i < 10:
    i += 1
    print(i)
else:
    i += 1
    print('Finished at evaluation', i)

1
2
3
4
5
6
7
8
9
10
Finished at evaluation 11


As you can observe in the above cell, the while statement evaluated the expression `i < 10` exactly 11 times. The first 10 times, the suite was executed because `i` was less than `10`. At the final evaluation `i` was exactly equal to `10`, therefore the `else` clause was executed, we then incremented `i` one final time before passing the value to a `print` procedure.

I encourage you to expiriment with the `while` statement as it is. afterward we will consider some additional control flow which we can use in the suite.

In [531]:
i = 0

while i < 10:
    i += 1
    
    if i % 2 == 1:
        continue
    
    print(i)
    
    if i == 10:
        break
else:
    print('I will never execute')


2
4
6
8
10


Above, you can observe the effect of two new statements which are unique to "loops" (such as the loop created by the `while` statement), `break` and `continue`.

> A break statement executed in the first suite terminates the loop without executing the `else` clause’s suite. A continue statement executed in the first suite skips the rest of the suite and goes back to testing the expression.

Therefore, in the above example, the while statement evaluated the expression `i < 10` exactly _**10**_ times, not 11 because of the `break` statement executed when on the eleventh iteration. Likewise, the suite only executed the `print` procedure 5 of 10 possible times, and only on the even value iterations of `i`. This was because of the `continue` statement which executed whenever `i` was an odd number, `i % 2 == 1`.

I encourage you to continue expirimenting with the `while` statement. Afterward we can consider the more complex `for` statement.

#### 2.1.8 For

> The for statement is used to iterate over the elements of a sequence (such as a string, tuple or list) or other iterable object:

Now that you see how control flow with comound statements works, this one should be a walk in the park. Consider the following cells.

In [533]:
a_string = "Hello, world!"

for character in a_string:
    print(character)
else:
    print("done")

H
e
l
l
o
,
 
w
o
r
l
d
!
done


Once again we observe a statement with two clauses, the first being:

```py
for character in a_string:
    print(character)
```

And the second being:

```py
else:
    print("done")
```

The `else` clause behaves as expected. However, our first clause differs from what we have observed in any other clause until this point. Consider the evaluation of the expression list `a_string` as described in the below documentation.

> The expression list is evaluated once; it should yield an iterable object. An iterator is created for the result of the expression list. The suite is then executed once for each item provided by the iterator, in the order returned by the iterator. Each item in turn is assigned to the target list _**(`character` in our example)**_ using the standard rules for assignments (see [Assignment statements](https://docs.python.org/3/reference/simple_stmts.html#assignment) [#2.1.2](#2.1.2-Assignments)), and then the suite is executed. When the items are exhausted (which is immediately when the sequence is empty or an iterator raises a `StopIteration` exception), the suite in the `else` clause, if present, is executed, and the loop terminates.

Yes, the `for` statement is not looking for a true evaluation, rather it is looking for an _iterable object_. We've seen a lot of those in this notebook. For instance, recall that `str` is an iterable sequence, as demonstrated above.

Observe the following cells to see how the `for` statement iterates over a collection such as the `OrderedDict` and another sequence such as a `tuple`.

In [547]:
ordered_dictionary = collections.OrderedDict()

ordered_dictionary['f'] = 6
ordered_dictionary['e'] = 5
ordered_dictionary['d'] = 4
ordered_dictionary['c'] = 3
ordered_dictionary['b'] = 2
ordered_dictionary['a'] = 1

for key in ordered_dictionary:
    if key == 'b':
        continue
    
    print(key)
    
    if key == 'a':
        break
else:
    print("done")

f
e
d
c
a


In [550]:
t = (1, 2, 3, 4, 5)

for value in t:
    if value == 4:
        continue
    
    print(value)
    
    if value == 5:
        break
else:
    print("done")

1
2
3
5


We observe here similar behaviour to that of the `while` statement, this is expected becuase `while` and `for` statements both create similar loops, though the _action_ taken to create those loops is completely different.

> A `break` statement executed in the first suite terminates the loop without executing the `else` clause’s suite. A `continue` statement executed in the first suite skips the rest of the suite and continues with the next item, or with the `else` clause if there is no next item.

Therefore, the outcome is similar to what we experienced in the case of the `while` statement.

Now you have mastered the traditional control flow constructs, with this knowledge you can already build complete Python programs. However, I want you to take a moment to think of what a program would look like, had you only the above conceptual tools at your disposal.

One problem you would face is that the code would be completely [_monolithic_](https://en.wikipedia.org/wiki/Monolithic_application). Just endless lines of control flow, without any organized structure. Worst yet, you have not learned to write any reusable, extendable (inheritable), or composable code. Such code would be a nightmare to maintain.

We don't want that.

Professionals usually want to write clean, efficient, modular, and optimized code. Let's consider first the backbones of such practices: functions and classes.

#### 2.1.9 Function definitions

We've talked a lot about functions already. Though you haven't written any yourself, you've read some of mine, for instance our `factorial` function.

You've also come to know that some functions are also called procedures, in Python you saw that this was when a function returned the `NoneType`.

So what _is_ a function definition?

> A function definition is an executable statement. Its execution binds the function name in the current local namespace to a function object (a wrapper around the executable code for the function). This function object contains a reference to the current global namespace as the global namespace to be used when the function is called.

> The function definition does not execute the function body; this gets executed only when the function is called.

So, functions are reusable blocks of code that can be called arbitrarily. Functions may define zero or more parameters, for instance, the following function defines 2:

```py
def add(a=1, b=1):
    """Adds b to a.

    Args:
    a: an int.
    b: an int.

    Returns: a plus b
    """
    return a + b
```

What's new here? Well, while the body of the function is nothing new to you, the head contains something interesting, `a=1, b=1`. What is this? Well, of course these are the same parameters you've read up until this point, but now they have _default parameter values_.

> When one or more parameters have the form _parameter `=` expression_, the function is said to have “default parameter values.” For a parameter with a default value, the corresponding argument may be omitted from a call, in which case the parameter’s default value is substituted. If a parameter has a default value, all following parameters up until the “`*`” must also have a default value — this is a syntactic restriction that is not expressed by the grammar.

> Default parameter values are evaluated from left to right when the function definition is executed. This means that the expression is evaluated once, when the function is defined, and that the same “pre-computed” value is used for each call. This is especially important to understand when a default parameter is a mutable object, such as a list or a dictionary: if the function modifies the object (e.g. by appending an item to a list), the default value is in effect modified. This is generally not what was intended. A way around this is to use None as the default, and explicitly test for it in the body of the function.

> A function call always assigns values to all parameters mentioned in the parameter list, either from position arguments, from keyword arguments, or from default values.

In the cell below, I want you to write a function definition of your own. It can do anything you want, take as many parameters as you want, and return whatever you want. But, I want you to write it yourself. At the moment, `my_function` is a useless procedure that does nothing but return `None`.

If you need help thinking of something creative, why not consider some mathematical functions, such as the [sigmoid function](https://en.wikipedia.org/wiki/Sigmoid_function).

In [551]:
def my_function():
    """Does nothing.

    Args:

    Returns: None
    """
    return None

Now let's [call](https://docs.python.org/3/reference/expressions.html#calls) `my_function`. Remember to include any required arguments (those are what we call the corresponding values for your predefined parameters!)

In [552]:
my_function()

I'm sure you've written something very meaningful! Great work!

Likely you found that functions are not so complicated after all. Aren't they basically just wrappers for everything else we've been doing this whole time? Yes, exactly, you're on the right track. Functions are neat little containers in which we can store reusable code.

What you've made, regardless of how clean and optimized it is, is a great step towards professional Python programming.

Next, let's consider class definitions.

#### 2.1.10 Class definitions